### ISSUE TITLE
showing "missing things"

### ISSUE THREAD

**Issue by krishan-here** [matthewbrown62/pagespeed#1]
i am cloning this project and install all dependencies but when i run this it shows "missing things"
please help me how to run this in my local server

**Comment by matthewbrown62** [comment]
This is meant to be installed as a slack bot and get google pagespeed stats from a slack command not as a service to be served from your localhost (unless you can get slack to make a request to your localhost). 

The "missing things" comes from the slack verification service. So all requests to all routes go through this service to check to see if there are slack signature and timestamp headers. I've pushed a change to give a clearer error message when those are missing. 

I've also added a readme for basic setup instructions.
